## Introduction to `astropy.coordinates`
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Danselem/brics_astro/blob/main/Week4/02_astropy_coordinates.ipynb)


Now that we have a solid understanding of `astropy.units` and how to represent physical quantities with consistent, meaningful units, we can move forward to a central topic in astronomical computing: **celestial coordinate systems**.

The `astropy.coordinates` subpackage provides a powerful and flexible framework for representing and transforming astronomical positions and motions. It allows astronomers to specify positions of objects in various coordinate systems, convert between them, and perform operations such as angular separations, projections, and velocity calculations.

This module is essential for tasks involving:
- Sky positions (e.g., RA/Dec, Galactic coordinates)
- Proper motions and radial velocities
- Coordinate transformations (e.g., ICRS ↔ Galactic ↔ AltAz)
- Observation planning and target tracking
- Parsing, formatting, and aligning catalogs

Behind the scenes, `astropy.coordinates` is fully integrated with `astropy.units`, so all angles, distances, and velocities are unit-aware, ensuring physical and computational consistency.

In this section, we will focus on the fundamental functionality of the `astropy.coordinates` module — the tools most commonly used to define, interpret, and convert astronomical positions. Mastering these basic elements will be essential for working with astronomical databases and sky catalogs later, particularly when using tools such as `astroquery`.


**Note**
If you are running this jupyter notebook from Colab, then run the next cell by pressing `SHIFT+ENTER` to install the required packages for this notebook. Otherwise, skip the next cell.

---

**中文**

##`astropy.coordinates`简介
[![在 Colab 中打开](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Danselem/brics_astro/blob/main/Week4/02_astropy_coordinates.ipynb)


现在我们对 `astropy.units` 以及如何用一致的、有意义的单位表示物理量有了深入的了解，我们可以继续讨论天文计算的中心主题：**天体坐标系**。

`astropy.coordinates` 子包提供了一个强大而灵活的框架来表示和转换天文位置和运动。它允许天文学家指定物体在各种坐标系中的位置，在它们之间进行转换，并执行诸如角距、投影和速度计算等操作。

该模块对于涉及以下任务至关重要：
- 天空位置（例如，赤经/赤纬、银河坐标）
- 自行和径向速度
- 坐标变换（例如 ICRS ↔ Galicate ↔ AltAz）
- 观测计划和目标跟踪
- 解析、格式化和对齐目录

在幕后，`astropy.coordinates` 与`astropy.units` 完全集成，因此所有角度、距离和速度都是单位感知的，确保物理和计算的一致性。

在本节中，我们将重点介绍`astropy.coordinates`模块的基本功能——最常用于定义、解释和转换天文位置的工具。掌握这些基本元素对于以后使用天文数据库和天空目录至关重要，特别是在使用 `astroquery` 等工具时。


**注意**
如果您从 Colab 运行此 jupyter 笔记本，请按 `SHIFT+ENTER` 运行下一个单元以安装此笔记本所需的软件包。否则，跳过下一个单元格。


In [ ]:
!pip install -q astropy

In [1]:
from astropy import units as u
from astropy.coordinates import SkyCoord
import numpy as np

coord = SkyCoord(ra=138.0108*u.degree, dec= -64.8625 *u.degree, frame='icrs') #NGC 2808
print(coord)
print(type(coord))

<SkyCoord (ICRS): (ra, dec) in deg
    (138.0108, -64.8625)>
<class 'astropy.coordinates.sky_coordinate.SkyCoord'>


In this cell, we create an object of the `SkyCoord` class from the `astropy.coordinates` module to represent the sky position of the globular cluster **NGC 2808**.

We provide:
- **Right Ascension (RA)**: 138.0108 degrees  
- **Declination (Dec)**: −64.8625 degrees  
- **Coordinate frame**: `'icrs'` (International Celestial Reference System), the standard celestial frame based on extragalactic reference points

By explicitly attaching the unit `u.degree` to each value, we ensure unit consistency and enable the coordinate object to interact properly with other tools in the `astropy` ecosystem.

The resulting `SkyCoord` object encapsulates both position and reference frame information, and serves as the foundation for coordinate transformations, distance associations, proper motion handling, and querying astronomical databases using tools like `astroquery`.

---

**中文**

在此单元中，我们从 `astropy.coordinates` 模块创建 `SkyCoord` 类的对象来表示球状星团 **NGC 2808** 的天空位置。

我们提供：
- **赤经 (RA)**：138.0108 度  
- **赤纬（Dec）**：−64.8625 度  
- **坐标系**：`'icrs'`（国际天球参考系），基于河外参考点的标准天球坐标系

通过将单位`u.degree`显式附加到每个值，我们确保单位一致性并使坐标对象能够与`astropy`生态系统中的其他工具正确交互。

生成的 `SkyCoord` 对象封装了位置和参考系信息，并作为坐标变换、距离关联、自行处理以及使用 `astroquery` 等工具查询天文数据库的基础。


In [2]:
#Warning: astropy.coordinates can digest any coordinate system — keep your fingers away from the input!
coord = SkyCoord(138.0108, -64.8625, frame='icrs', unit='deg')
print(coord)
coord = SkyCoord('09h12m2.6s', '-64d51m45s', frame='icrs')
print(coord)
coord = SkyCoord('09 12 2.6 -64 51 45', unit=(u.hourangle, u.deg))
print(coord)
coord = SkyCoord('09:12:2.6 -64:51:45', unit=(u.hourangle, u.deg))
print(coord)

<SkyCoord (ICRS): (ra, dec) in deg
    (138.0108, -64.8625)>
<SkyCoord (ICRS): (ra, dec) in deg
    (138.01083333, -64.8625)>
<SkyCoord (ICRS): (ra, dec) in deg
    (138.01083333, -64.8625)>
<SkyCoord (ICRS): (ra, dec) in deg
    (138.01083333, -64.8625)>


In [3]:
print(coord.ra,coord.dec)
print(type(coord.ra))
print(type(coord.dec))

138d00m39s -64d51m45s
<class 'astropy.coordinates.angles.core.Longitude'>
<class 'astropy.coordinates.angles.core.Latitude'>


In this cell, we retrieve the stored **Right Ascension** and **Declination** from the `SkyCoord` object using the `.ra` and `.dec` attributes.

These attributes return `Quantity` objects from `astropy.units`, which means they retain both the numerical value and the unit (in this case, degrees). This allows for safe arithmetic, conversion to other units, and precise control over formatting.

By printing `type(coord.ra)`, we confirm that the output is not just a number but an instance of `astropy.units.Quantity`. This reinforces the fact that `SkyCoord` maintains full unit awareness internally.

---

**中文**

在此单元格中，我们使用 `.ra` 和 `.dec` 属性从 `SkyCoord` 对象检索存储的 **赤经** 和 **赤纬**。

这些属性从 `astropy.units` 返回 `Quantity` 对象，这意味着它们保留数值和单位（在本例中为度）。这样可以进行安全算术、转换为其他单位以及精确控制格式。

通过打印`type(coord.ra)`，我们确认输出不仅仅是一个数字，而是`astropy.units.Quantity`的一个实例。这强化了 `SkyCoord` 在内部保持完整的单元意识的事实。


In [4]:
print(coord.ra.hour,coord.dec.deg)
print(type(coord.ra.hour))


9.200722222222224 -64.8625
<class 'numpy.float64'>


In this cell, we extract the **Right Ascension** and **Declination** from the `SkyCoord` object, but in alternative representations:

- `.ra.hour` converts the right ascension from degrees to **hours**, since RA is traditionally measured in hours, minutes, and seconds in astronomy (1 hour = 15 degrees).
- `.dec.deg` simply returns the declination in decimal degrees, which is the default angular unit for declination.

Note that `.ra.hour` returns a plain Python float — it strips away the unit metadata and gives only the numerical value in hours. This can be useful for certain formatting or external tools, but lacks the unit safety of `Quantity` objects.

By printing `type(coord.ra.hour)`, we verify that the result is no longer a `Quantity` but a standard `float`.

---

**中文**

在此单元格中，我们从 `SkyCoord` 对象中提取 **赤经** 和 **赤纬**，但采用替代表示形式：

- `.ra.hour` 将赤经从度转换为 **小时**，因为 RA 传统上在天文学中以小时、分钟和秒来测量（1 小时 = 15 度）。
- `.dec.deg` 仅返回以十进制为单位的赤纬，这是赤纬的默认角度单位。

请注意，`.ra.hour` 返回一个普通的 Python 浮点数 — 它去掉了单位元数据，只给出以小时为单位的数值。这对于某些格式化或外部工具很有用，但缺乏 `Quantity` 对象的单元安全性。

通过打印`type(coord.ra.hour)`，我们验证结果不再是`Quantity`，而是标准`float`。


In [5]:
print(coord.ra.hms)
print(coord.dec.dms)

hms_tuple(h=np.float64(9.0), m=np.float64(12.0), s=np.float64(2.600000000004883))
dms_tuple(d=np.float64(-64.0), m=np.float64(-51.0), s=np.float64(-44.99999999998977))


In this cell, we access the `.ra.hms` attribute of the `SkyCoord` object.

The `.hms` property returns the **hours**, **minutes**, and **seconds** representation of the Right Ascension (RA) as a named tuple:  
`hms = (hour, minute, second)`

This format is especially useful in astronomical catalogs, telescope pointing systems, and human-readable reports where RA is traditionally expressed in sexagesimal units.

Unlike `.ra.hour`, which returns a single float in hours, `.ra.hms` provides a full breakdown for easy formatting or display:

- `coord.ra.hms.h`: hours  
- `coord.ra.hms.m`: minutes  
- `coord.ra.hms.s`: seconds

The resulting values are pure floats, not `Quantity` objects, so units are implied by context rather than enforced.

---

**中文**

在此单元格中，我们访问`SkyCoord` 对象的`.ra.hms` 属性。

`.hms` 属性返回赤经 (RA) 的 **小时**、**分钟** 和 **秒** 表示形式作为命名元组：  
@@内联3@@

这种格式在天文目录、望远镜指向系统和人类可读的报告中特别有用，其中 RA 传统上以六十进制单位表示。

与`.ra.hour`（以小时为单位返回单个浮点数）不同，`.ra.hms` 提供了完整的细分，以便于格式化或显示：

- `coord.ra.hms.h`：小时  
- `coord.ra.hms.m`：分钟  
- `coord.ra.hms.s`：秒

结果值是纯浮点数，而不是 `Quantity` 对象，因此单位是由上下文隐含的，而不是强制的。


In [6]:
print(coord.ra.radian,coord.dec.radian)

2.4087434450878074 -1.132064186074822


In this cell, we access the `.radian` attribute of the Right Ascension and Declination stored in the `SkyCoord` object.

- `.ra.radian` returns the Right Ascension in **radians**
- `.dec.radian` returns the Declination in **radians**

Both values are returned as standard Python floats (not `Quantity` objects), and the unit is implicitly understood to be **radians**.

This representation is useful when working with trigonometric functions from libraries like NumPy or SciPy, which expect input angles in radians. However, because units are no longer attached, it's important to track units manually and avoid unit mismatches.

---

**中文**

在此单元格中，我们访问存储在 `SkyCoord` 对象中的赤经和赤纬的 `.radian` 属性。

- `.ra.radian` 返回以 **弧度** 为单位的赤经
- `.dec.radian` 返回赤纬（以**弧度**为单位）

这两个值都作为标准 Python 浮点数（而不是 `Quantity` 对象）返回，并且单位隐式理解为 **弧度**。

当使用 NumPy 或 SciPy 等库中的三角函数时，这种表示非常有用，这些函数需要以弧度为单位的输入角度。但是，由于单位不再附加，因此手动跟踪单位并避免单位不匹配非常重要。


In [7]:
print(coord.to_string('decimal'))
print(coord.to_string('dms'))
print(coord.to_string('hmsdms'))

138.011 -64.8625
138d00m39s -64d51m45s
09h12m02.6s -64d51m45s


In this cell, we use the `.to_string()` method of the `SkyCoord` object to display the coordinates in various string formats.

The method formats the Right Ascension and Declination into human-readable strings using different notations:

- `coord.to_string('decimal')`  
  Returns RA and Dec as decimal degrees, separated by a space.  
  Example: `'138.0108 -64.8625'`

- `coord.to_string('dms')`  
  Returns both RA and Dec in **degrees:minutes:seconds (DMS)** format.  
  Example: `'138d00m38.88s -64d51m45s'`  
  This is useful when reporting coordinates in formats commonly used in catalogs or observational logs.

- `coord.to_string('hmsdms')`  
  Formats RA in **hours:minutes:seconds (HMS)** and Dec in **DMS**.  
  Example: `'09h12m2.60s -64d51m45s'`  
  This is the traditional astronomical format for sky coordinates.

These formatting options are especially useful when exporting results, generating catalogs, or matching coordinate formats from external datasets.

---

**中文**

在此单元格中，我们使用`SkyCoord`对象的`.to_string()`方法来以各种字符串格式显示坐标。

该方法使用不同的符号将赤经和赤纬格式化为人类可读的字符串：

-`coord.to_string('decimal')`  
  以十进制度数形式返回 RA 和 Dec，并以空格分隔。  
  示例：`'138.0108 -64.8625'`

-`coord.to_string('dms')`  
  以 **度:分:秒 (DMS)** 格式返回 RA 和 Dec。  
  示例：`'138d00m38.88s -64d51m45s'`  
  当以目录或观测日志中常用的格式报告坐标时，这非常有用。

-`coord.to_string('hmsdms')`  
  以 **小时:分钟:秒 (HMS)** 格式设置 RA，以 **DMS** 格式设置 Dec。  
  示例：`'09h12m2.60s -64d51m45s'`  
  这是天空坐标的传统天文格式。

当导出结果、生成目录或从外部数据集匹配坐标格式时，这些格式设置选项特别有用。


In [8]:
print(coord.galactic)

<SkyCoord (Galactic): (l, b) in deg
    (282.19166541, -11.25257989)>


In this cell, we access the `.galactic` attribute of the `SkyCoord` object to obtain the position of the same object (NGC 2808) in the **Galactic coordinate system**.

The `.galactic` attribute returns a new `SkyCoord` object representing the same physical location on the sky, but in terms of:

- **Galactic Longitude (`l`)** — measured in degrees, increasing in the direction of the Galactic rotation
- **Galactic Latitude (`b`)** — measured in degrees, positive above the Galactic plane

This transformation is handled internally by `astropy`, using the built-in coordinate transformation graph. The result remains a fully unit-aware `SkyCoord` object and can be further queried, transformed, or formatted like any other coordinate.

Galactic coordinates are especially useful when studying the structure and components of the Milky Way.

---

**中文**

在此单元格中，我们访问 `SkyCoord` 对象的 `.galactic` 属性，以获取同一对象 (NGC 2808) 在 **银河坐标系** 中的位置。

`.galactic` 属性返回一个新的 `SkyCoord` 对象，表示天空上的相同物理位置，但表示为：

- **银河经度 (`l`)** — 以度为单位测量，沿银河旋转方向增加
- **银河纬度 (`b`)** — 以度为单位测量，在银河平面上方为正值

此转换由 `astropy` 使用内置坐标转换图在内部处理。结果仍然是一个完全单位感知的 `SkyCoord` 对象，并且可以像任何其他坐标一样进一步查询、转换或格式化。

在研究银河系的结构和组成时，银河坐标特别有用。


In [9]:
NGC_2808 = SkyCoord.from_name("NGC 2808")
print(NGC_2808)

<SkyCoord (ICRS): (ra, dec) in deg
    (138.01291667, -64.8635)>


In this cell, we use `SkyCoord.from_name()` to automatically retrieve the celestial coordinates of **NGC 2808** by querying the **SIMBAD** astronomical database.

This method sends a network request and resolves the name `"NGC 2808"` to its ICRS (RA/Dec) coordinates. The returned result is a standard `SkyCoord` object, ready for further use.

This feature is especially helpful when working with named astronomical objects, saving time and reducing errors compared to manually entering coordinates.

> **Pro tip**: Even if you're banned from Google or can't load Wikipedia, you can still resolve star cluster positions like a pro! Thanks to `astropy` and SIMBAD!

---

**中文**

在此单元格中，我们使用 `SkyCoord.from_name()` 通过查询 **SIMBAD** 天文数据库自动检索 **NGC 2808** 的天体坐标。

此方法发送网络请求并将名称 `"NGC 2808"` 解析为其 ICRS (RA/Dec) 坐标。返回的结果是一个标准的`SkyCoord`对象，可供进一步使用。

在处理命名天文物体时，此功能特别有用，与手动输入坐标相比，可以节省时间并减少错误。

> **专业提示**：即使您被 Google 禁止或无法加载维基百科，您仍然可以像专业人士一样解析星团位置！感谢`astropy` 和 SIMBAD！


In [10]:
ra_deg = np.array([6.023625, 13.18875, 78.528625, 81.046667, 138.0108,
                   201.6975, 229.63875, 250.4225, 265.175833, 322.493958])
dec_deg = np.array([-72.081283, -26.582806, -40.046875, -24.524139, -64.8625,
                    -47.479722, 2.081, 36.460278, -53.674694, 12.16625])

cluster_names = np.array([
    "NGC 104",    # 47 Tucanae
    "NGC 288",
    "NGC 1851",
    "NGC 1904",   # M79
    "NGC 2808",
    "NGC 5139",   # Omega Centauri
    "NGC 5904",   # M5
    "NGC 6205",   # M13
    "NGC 6397",
    "NGC 7078"    # M15
])

dist_kpc = np.array([
    4.5, 8.9, 12.1, 12.9, 9.6,
    5.2, 7.5, 7.7, 2.3, 10.4
])  #GAIA/DR3 distances

cluster_coords = SkyCoord(ra=ra_deg * u.deg, dec=dec_deg * u.deg, distance = dist_kpc*u.kpc, frame='icrs') # Create a SkyCoord array from NumPy arrays
print(cluster_coords) #RA and Dec in degrees for 10 globular clusters (J2000)

<SkyCoord (ICRS): (ra, dec, distance) in (deg, deg, kpc)
    [(  6.023625, -72.081283,  4.5), ( 13.18875 , -26.582806,  8.9),
     ( 78.528625, -40.046875, 12.1), ( 81.046667, -24.524139, 12.9),
     (138.0108  , -64.8625  ,  9.6), (201.6975  , -47.479722,  5.2),
     (229.63875 ,   2.081   ,  7.5), (250.4225  ,  36.460278,  7.7),
     (265.175833, -53.674694,  2.3), (322.493958,  12.16625 , 10.4)]>


### Using NumPy Arrays with `SkyCoord`

In this cell, we demonstrate how to create a `SkyCoord` object using **NumPy arrays** for multiple celestial objects.

We define:
- An array of **Right Ascension** (`ra_deg`) values in degrees  
- An array of **Declination** (`dec_deg`) values in degrees  
- An array of **distances** (`dist_kpc`) in kiloparsecs  
- A list of **names** for 10 well-known globular clusters

By passing these arrays directly into the `SkyCoord` constructor along with their appropriate units, we create a structured collection of coordinates. Each element includes full 3D spatial information: angular position (RA, Dec) and distance.

This approach allows efficient, vectorized operations on many coordinates at once and is ideal for working with astronomical catalogs and large datasets.

---

**中文**

### 将 NumPy 数组与 `SkyCoord` 一起使用

在此单元中，我们演示如何使用 **NumPy 数组** 为多个天体创建 `SkyCoord` 对象。

我们定义：
- **赤经** (`ra_deg`) 值（以度为单位）的数组  
- **偏角** (`dec_deg`) 值（以度为单位）的数组  
- 以千秒差距为单位的**距离** (`dist_kpc`) 数组  
- 10 个著名球状星团的**名称**列表

通过将这些数组及其适当的单位直接传递到 `SkyCoord` 构造函数中，我们创建了一个结构化的坐标集合。每个元素都包含完整的 3D 空间信息：角度位置（RA、Dec）和距离。

这种方法允许同时在多个坐标上进行高效的矢量化操作，非常适合处理天文目录和大型数据集。


In [11]:
sep_3d = cluster_coords[0].separation_3d(cluster_coords[9])
sep_ang = cluster_coords[0].separation(cluster_coords[9])
print(f"3D distance between {cluster_names[0]} and {cluster_names[9]}: {sep_3d.to(u.kpc):.2f}")
print(f"Angular separation {cluster_names[0]} and {cluster_names[9]}: {sep_ang.to(u.degree):.2f}")

3D distance between NGC 104 and NGC 7078: 11.26 kpc
Angular separation NGC 104 and NGC 7078: 89.00 deg


### Measuring 3D Distance Between Two Globular Clusters

In this cell, we compute the **true spatial separation** between two globular clusters using their full 3D coordinates.

Specifically, we call:

```python
cluster_coords[0].separation_3d(cluster_coords[9])
```

This computes the **Euclidean distance in 3D space** between the first cluster (`NGC 104`) and the last cluster (`NGC 7078`) in our list.

Unlike angular separation (which only considers position on the sky), `.separation_3d()` uses both:
- Angular coordinates (RA, Dec)
- Radial distances (in kiloparsecs)

The result is returned as a `Quantity` with physical units (e.g., `kpc`), giving the **true line-of-sight separation** between the two objects in three-dimensional space.

---

**中文**

### 测量两个球状星团之间的 3D 距离

在此单元中，我们使用完整的 3D 坐标计算两个球状星团之间的**真实空间分离**。

具体来说，我们称之为：

@@代码块0@@

这将计算列表中第一个簇 (`NGC 104`) 和最后一个簇 (`NGC 7078`) 之间的 **3D 空间中的欧几里得距离**。

与角度分离（仅考虑天空上的位置）不同，`.separation_3d()` 使用两者：
- 角坐标（RA、Dec）
- 径向距离（以千秒差距为单位）

结果以具有物理单位的 `Quantity` 形式返回（例如 `kpc`），从而在三维空间中的两个对象之间提供**真实的视线分离**。


### Working with Angles in `astropy.coordinates`

In astronomy, angles are everywhere — from sky coordinates (RA/Dec, Alt/Az) to angular separations, field of view, proper motions, and more. To handle such angular quantities with both **unit safety** and **astronomical precision**, `astropy.coordinates` provides the `Angle` class.

The `Angle` object is a specialized form of `Quantity` designed specifically for angular values. It allows:

- Flexible creation from degrees, radians, hours, DMS, or HMS strings
- Easy conversion between angular formats
- Safe arithmetic (addition, subtraction, wrapping)
- High-precision comparison and transformations
- Use of custom wrapping and normalization (e.g. `wrap_at(180*u.deg)`)

Because `Angle` is fully unit-aware and interoperable with `SkyCoord`, it's ideal for precise and readable angular computations — whether you're rotating frames, computing angular distances, or converting between coordinate systems.

In short, the `Angle` class gives you both the **power of astropy.units** and the **expressiveness of astronomical angular conventions**, all in one object.

---

**中文**

### 在`astropy.coordinates` 中使用角度

在天文学中，角度无处不在——从天空坐标（RA/Dec、Alt/Az）到角距、视场、自行等等。为了以**单位安全**和**天文精度**处理此类角度量，`astropy.coordinates` 提供了 `Angle` 类。

`Angle` 对象是`Quantity` 的特殊形式，专为角度值而设计。它允许：

- 从度数、弧度、小时、DMS 或 HMS 字符串灵活创建
- 角度格式之间轻松转换
- 安全算术（加法、减法、换行）
- 高精度比较和转换
- 使用自定义包装和规范化（例如`wrap_at(180*u.deg)`）

由于 `Angle` 完全具有单位感知能力并且可与 `SkyCoord` 互操作，因此它非常适合精确且可读的角度计算 — 无论您是旋转框架、计算角距离还是在坐标系之间进行转换。

简而言之，`Angle` 类为您提供了 **astropy.units** 的强大功能** 和 **天文角度约定的表现力**，所有这些都在一个对象中。


In [12]:
from astropy.coordinates import Angle
Angle('10.2345d')              # String with 'd' abbreviation for degrees
Angle(['10.2345d', '-20d'])    # Array of strings
Angle('1:2:30.43 degrees')     # Sexagesimal degrees
Angle('1 2 0 hours')           # Sexagesimal hours
Angle(np.arange(1., 8.), unit=u.deg)  # Numpy array from 1..7 in degrees
Angle('1°2′3″')               # Unicode degree, arcmin and arcsec symbols
Angle('1°2′3″N')               # Unicode degree, arcmin, arcsec symbols and direction
Angle('1d2m3.4s')              # Degree, arcmin, arcsec.
Angle('1d2m3.4sS')              # Degree, arcmin, arcsec, direction.
Angle('-1h2m3s')               # Hour, minute, second
Angle('-1h2m3sW')               # Hour, minute, second, direction
Angle(10.2345 * u.deg)         # From a Quantity object in degrees
Angle(Angle(10.2345 * u.deg))  # From another Angle object

<Angle 10.2345 deg>

In [13]:
a1 = Angle("10d30m")
a2 = Angle("2d15m")
a3 = a1 + a2
a4 = a1 - a2
print(f"Sum: {a3}")
print(f"Difference: {a4}")

Sum: 12.75 deg
Difference: 8.25 deg


### Angle Arithmetic

`Angle` objects support standard arithmetic:
- Addition and subtraction
- Multiplication/division by scalars
- Array operations

This is especially useful when calculating angular distances or adjusting positions.

---

**中文**

### 角度算术

`Angle`对象支持标准算术：
- 加法和减法
- 标量乘法/除法
- 数组操作

这在计算角距离或调整位置时特别有用。


# Summary: Core Concepts of `astropy.coordinates`

In this lesson, we explored the fundamental capabilities of the `astropy.coordinates` subpackage:

- Creation of coordinate objects using `SkyCoord` with scalar and array inputs
- Representation and formatting of celestial coordinates in degrees, radians, hms/dms
- Transformations between coordinate systems (e.g., ICRS, Galactic)
- Extraction of coordinate attributes (`ra`, `dec`, `galactic`, `.radian`, `.hms`, etc.)
- Name-based lookups using `SkyCoord.from_name()`
- Angular and 3D spatial separation calculations
- Vectorized coordinate handling using NumPy arrays

---

## Additional Topics Worth Exploring

We have only touched the surface of what `astropy.coordinates` can do. The following topics are highly recommended for further study:

### Coordinate Systems and Frame Transformations
- Full transformation graph between supported frames
- Custom frames and intermediate transformations  
[Docs: Transforming Coordinates](https://docs.astropy.org/en/stable/coordinates/transforming.html)

### AltAz and Observational Coordinates
- Working with `AltAz` frame for ground-based observations
- Using `EarthLocation` and `Time` for observer-specific calculations  
[Docs: AltAz Coordinates](https://docs.astropy.org/en/stable/coordinates/altaz.html)

### EarthLocation and Time-Aware Coordinates
- Creating observer locations with `EarthLocation`
- Combining with `Time` for precision observation planning  
[Docs: EarthLocation](https://docs.astropy.org/en/stable/api/astropy.coordinates.EarthLocation.html)

### Proper Motions and Radial Velocities
- Representing space motion using `proper_motion` and `radial_velocity`
- Time propagation of position and velocity  
[Docs: Motions](https://docs.astropy.org/en/stable/coordinates/motion.html)

### Angle Utilities
- Use of `Angle`, `Latitude`, and `Longitude` classes
- Trigonometric operations, formatting, wrapping  
[Docs: Angle Classes](https://docs.astropy.org/en/stable/api/astropy.coordinates.Angle.html)

---

## Recommendations

- Use `SkyCoord` for all celestial position representations.
- Always use physical units with `astropy.units` for clarity and safety.
- Leverage vectorization with NumPy for working with large coordinate sets.
- Understand when and how to use coordinate transformations.
- Explore observational frames (`AltAz`, `Geocentric`, `Heliocentric`) for real-world scenarios.

For the full documentation, see:  
[https://docs.astropy.org/en/stable/coordinates/index.html](https://docs.astropy.org/en/stable/coordinates/index.html)

---

**中文**

# 总结：`astropy.coordinates`的核心概念

在本课中，我们探讨了 `astropy.coordinates` 子包的基本功能：

- 使用带有标量和数组输入的 `SkyCoord` 创建坐标对象
- 以度、弧度、hms/dms 为单位的天体坐标的表示和格式
- 坐标系之间的转换（例如，ICRS、银河系）
- 坐标属性的提取（`ra`、`dec`、`galactic`、`.radian`、`.hms`等）
- 使用`SkyCoord.from_name()`进行基于名称的查找
- 角度和 3D 空间分离计算
- 使用 NumPy 数组进行矢量化坐标处理

---

## 其他值得探索的主题

我们只接触了 `astropy.coordinates` 功能的表面。强烈建议进一步研究以下主题：

### 坐标系和框架变换
- 支持的帧之间的完整转换图
- 自定义框架和中间转换  
[文档：变换坐标](https://docs.astropy.org/en/stable/coordinates/transforming.html)

### AltAz 和观测坐标
- 使用`AltAz`框架进行地面观测
- 使用`EarthLocation`和`Time`进行特定于观察者的计算  
[文档：AltAz 坐标](https://docs.astropy.org/en/stable/coordinates/altaz.html)

### 地球位置和时间感知坐标
- 使用`EarthLocation`创建观察者位置
- 结合`Time`进行精准观测规划  
[文档：EarthLocation](https://docs.astropy.org/en/stable/api/astropy.coordinates.EarthLocation.html)

### 自行和径向速度
- 使用`proper_motion`和`radial_velocity`表示空间运动
- 位置和速度的时间传播  
[文档：运动](https://docs.astropy.org/en/stable/coordinates/motion.html)

### 角度实用程序
- 使用`Angle`、`Latitude` 和`Longitude` 类
- 三角运算、格式化、换行  
[文档：角度类](https://docs.astropy.org/en/stable/api/astropy.coordinates.Angle.html)

---

## 建议

- 对所有天体位置表示使用`SkyCoord`。
- 为了清晰和安全，请始终使用带 `astropy.units` 的物理单位。
- 利用 NumPy 的矢量化来处理大型坐标集。
- 了解何时以及如何使用坐标变换。
- 探索真实场景的观察框架（`AltAz`、`Geocentric`、`Heliocentric`）。

有关完整文档，请参阅：  
[https://docs.astropy.org/en/stable/coordinates/index.html](https://docs.astropy.org/en/stable/coordinates/index.html)
